version: "3.9"
services:
  transactions:
    platform: linux/amd64
    build: .
    ports:
      - "465:465"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass